### ISSUE TITLE
nav_cloningのnumpyに関するエラー

### ISSUE THREAD

**Issue by nkm071** [nkm071/end-to-end_with_Generate-day-to-night-images#6]
nav_cloningに関わるエラーであるものの個人環境の問題であることとdockerでday-to-nightを扱う動機の一つになるため本リポジトリで扱う．コマンド1を動作させたところエラーメッセージが出力された．原因として考えられることは以前動作させたときとはpythonの環境が異なる可能性があげられる.

コマンド1
`roslaunch nav_cloning nav_cloning_sim.launch  `

```
process[nav_cloning_node-1]: started with pid [9316]
Traceback (most recent call last):
  File "/home/neko/nav_cloning_ws/src/nav_cloning/scripts/nav_cloning_node.py", line 12, in <module>
    from skimage.transform import resize
  File "/home/neko/.local/lib/python3.8/site-packages/skimage/__init__.py", line 127, in <module>
    from .util.dtype import (img_as_float32,
  File "/home/neko/.local/lib/python3.8/site-packages/skimage/util/__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File "/home/neko/.local/lib/python3.8/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/usr/lib/python3/dist-packages/dask/array/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/lib/python3/dist-packages/dask/array/core.py", line 28, in <module>
    from . import chunk
  File "/usr/lib/python3/dist-packages/dask/array/chunk.py", line 7, in <module>
    from . import numpy_compat as npcompat
  File "/usr/lib/python3/dist-packages/dask/array/numpy_compat.py", line 21, in <module>
    np.divide(0.4, 1, casting="unsafe", dtype=np.float),
  File "/home/neko/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[nav_cloning_node-1] process has died [pid 9316, exit code 1, cmd /home/neko/nav_cloning_ws/src/nav_cloning/scripts/nav_cloning_node.py __name:=nav_cloning_node __log:=/home/neko/.ros/log/e5d6ffbc-7002-11ef-832c-3312ce67941d/nav_cloning_node-1.log].
log file: /home/neko/.ros/log/e5d6ffbc-7002-11ef-832c-3312ce67941d/nav_cloning_node-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete

```

**Comment by nkm071** [comment]
[こちらのREADME](https://github.com/nkm071/nav_cloning)にあるコマンドを使用することでnav_cloningが動作する環境に戻すことができた．
```
pip3 install torch torchvision scikit-image tensorboard
pip3 install --upgrade numpy scikit-image
```
